const CHAT_MESSAGE = "CHAT_MESSAGE";
const USER_TYPING = "USER_TYPING";
const USERS_ONLINE = "USERS_ONLINE";
const DISCONNECT = "disconnect";
const USER_JOIN = "JOIN";
const PRIVATE_MESSAGE = "PRIVATE_MESSAGE";
const AUTHENTICATE = "AUTHENTICATE";
const AUTHENTICATED = "AUTHENTICATED";
const UNAUTHORIZED = "unauthorized";
const CONNECTION = "connection";

module.exports = {
  USER_JOIN,
  CHAT_MESSAGE,
  USER_TYPING,
  USERS_ONLINE,
  DISCONNECT,
  PRIVATE_MESSAGE,
  AUTHENTICATE,
  AUTHENTICATED,
  UNAUTHORIZED,
  CONNECTION
};
